### ISSUE TITLE
improperly purged: p:not(:nth-child(n+3)) { color: green }

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/dropcss#13]
css:
```css
p:not(:nth-child(n+3)) { color: green }
```

html:
```html
<div id="root">
  <p>Hello World!</p>
  <p>Hello World!</p>
  <p>Hello World!</p>
  <p>Hello World!</p>
</div>
```
