### ISSUE TITLE
also test font: shorthand props when dropping unused @font-face

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/dropcss#25]
https://developer.mozilla.org/en-US/docs/Web/CSS/font

```css
@font-face {
  font-family: "Open Sans";
  src: url("/fonts/OpenSans-Regular-webfont.woff2") format("woff2"),
       url("/fonts/OpenSans-Regular-webfont.woff") format("woff");
}

body {
  font: italic small-caps normal 13px/150% Arial, 'Open Sans', Helvetica, sans-serif;
}
```
