### ISSUE TITLE
Crashes on font shorthand with custom properties

### ISSUE THREAD

**Issue by tornqvist** [leeoniya/dropcss#26]
A recent fix (https://github.com/leeoniya/dropcss/commit/8e27afdef0ccd579cce56c50580e21537ccc0855) for short hand font properties will throw an error if one is using custom properties.

E.g. this rule causes the regex in said commit to not match.

```css
.foo {
  font: var(--font-style) var(--font-weight) 1em/var(--line-height) var(--font-family);
}
```

**Comment by leeoniya** [comment]
thanks for the report, will take a look later today.

on a more general note, i wonder if it makes sense to resolve css vars. my initial thought is that it would open a big can of worms beyond the simple static example. also, was DropCSS incorrectly removing font-faces for you prior to this commit, and/or did you have them whitelisted?

**Comment by leeoniya** [comment]
ok, i've added custom props resolving in b414a669d3f143eaf3a3eebab429e48e5f84284c. seems to do okay in this test:

```html
<!doctype html>
<html>
  <head>
    <script src="../dist/dropcss.js"></script>
    <script>
      function run() {
        let clean = dropcss({
          html: `
            <html><body></body></html>
          `,
          css: `
            :root {
              --font-style: italic;
              --font-weight: bold;
              --line-height: 1.6em;
              --font-family: 'Open Sans';
            }

            @font-face {
              font-family: "Open Sans";
              src: url("/fonts/OpenSans-Regular-webfont.woff2") format("woff2"),
                   url("/fonts/OpenSans-Regular-webfont.woff") format("woff");
            }

            body {
              font: var(--font-style) var(--font-weight) 1em/var(--line-height) var(--font-family);
            }
          `,
        });

        console.log(clean.css);
      }
    </script>
  </head>
  <body>
    <button onclick="run()">run()</button>
  </body>
</html>
```

let me know how this works out.

**Comment by tornqvist** [comment]
Sorry, my example was a simplified version of my actual use case. We use custom properties for both the font shorthand and the individual properties. This is more in line with what I'm working with and it's unfortunately still crashing with this fix:

```css
:root {
  --font-style: italic;
  --font-weight: bold;
  --line-height: 1.6em;
  --font-family: 'Open Sans';
  --font: var(--font-style) var(--font-weight) 1em/var(--line-height) var(--font-family);
}

@font-face {
  font-family: "Open Sans";
  src: url("/fonts/OpenSans-Regular-webfont.woff2") format("woff2"),
        url("/fonts/OpenSans-Regular-webfont.woff") format("woff");
}

body {
  font: var(--font);
}
```
