### ISSUE TITLE
BEM + pseudo trips up custom var extraction: .a--b:hover{}

### ISSUE THREAD

**Issue by saltymouse** [leeoniya/dropcss#31]
Seems like there's some trouble parsing BEM selectors, namely the `--modifier` bit.

```javascript
const dropcss = require('dropcss');

let html = `
    <html>
        <head></head>
        <body>
          <div class="tab-table">
            <div class="tab-table__item">Tab 1</div>
            <div class="tab-table__item tab-table__item--new">Tab 2</div>
          </div>
        </body>
    </html>
`;

let css = `                                                                                           
.tab-table {
  display: flex;
  flex-flow: row nowrap;
  position: relative;
}

.tab-table__item {
  background: #494545;
  border-width: 0 .1rem;
  cursor: pointer;
  flex: 1 1 20%;
  flex-flow: column nowrap;
}

.tab-table__item--new::before {
  align-items: center;
  color: #fff;
  display: flex;
  justify-content: center;
}
`;

let cleaned = dropcss({
    html,
    css, 
});

console.log(cleaned);
/*
{ css: '.tab-table{display: flex;\n  flex-flow: row nowrap;\n  position: relative;}.tab-table__item{background: #494545;\n  border-width: 0 .1rem;\n  cursor: pointer;\n  flex: 1 1 20%;\n  flex-flow: column nowrap;}.tab-table__itemcolor: #fff;\n  display: flex;\n  justify-content: center;}',
  sels: 
   Set {
     '.tab-table',
     '.tab-table__item',
     '.tab-table__item--new::before' } }
*/
```

Formatted CSS to more clearly see what's going on:
```css
.tab-table {
  display: flex;
  flex-flow: row nowrap;
  position: relative;
}

.tab-table__item {
  background: #494545;
  border-width: 0 .1rem;
  cursor: pointer;
  flex: 1 1 20%;
  flex-flow: column nowrap;
}

.tab-table__itemcolor: #fff; /* should be `.tab-table__item--new::before {` */
display: flex;
justify-content: center;
}
```

dropcss version: `1.0.12`
node version: `10.16.0`
