### ISSUE TITLE
Always assume implicit tags are present

### ISSUE THREAD

**Issue by clarfon** [leeoniya/dropcss#35]
Right now, rules are removed if the document lacks `html`, `head`, or `body` tags, even though these are implicitly added in HTML 5. The parser should also assume the presence of these tags so that these rules aren't removed.

Example input HTML/CSS:

```html
<!DOCTYPE html>
<p>Hello, world!
```

```css
html { background: black; color: white }
p { margin: 1em }
```

Currently outputs CSS:

```css
p { margin: 1em }
```

Even though it should not remove the `html` selector.

Note that this also applies to `head` and `body`, e.g. `head title` will always be equivalent to `title` with extra specificity even if no `<head>` tag is present and `body p` will always be equivalent to `p` with extra specificity even if no `<body>` tag is present.
