### ISSUE TITLE
support custom property fallback values

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/dropcss#43]
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#Custom_property_fallback_values

```css
.three {
  background-color: var(--my-var, var(--my-background, pink));
--border-color: linear-gradient(to top, var(--secondary-color), var(--used-color, white));
}
```
